ourDatapathId: 01:02:03:04:05:06:07:08

applications:                  # config.ApplicationType
  - ControllerLogApplication
  - SwitchLogApplication
  - MultiSwitchApplication
  #- OneTransparentSwitchApplication
  #- P4ControlApplication

# Connection from TV to the Controller
upperLayerEndpoints:
  - name: OnosEndpoint
    type: OPENFLOW            # upperlayer.UpperLayerType
    ip: 127.0.0.1
    port: 6653
    reconnectInterval: 5000   # default: 10000 ms

# Connection from TV to the Switches
lowerLayerEndpoints:
  - name: OpenFlowSwitches
    type: OPENFLOW            # lowerlayer.LowerLayerType
    port: 6654
    switches:
      - dataplaneId: 1
        datapathId: 00:00:00:00:00:00:00:01
        tableMap:
            # [Our TableID towards Controller] : [TableID of Switch]
            0: 0
            4: 0
        portMap:
            #  [Local Port of Device] : [Our DataplaneID]
            3: 2
            4: 2
      - dataplaneId: 2
        datapathId: 00:00:00:00:00:00:00:02
        tableMap:
            # [Our TableID towards Controller] : [TableID of Switch]
            1: 0
            2: 1
        portMap:
            #  [Local Port of Device] : [Our DataplaneID]
            1: 1
            2: 1
#            3: 100
#            4: 100
#  - name: P4Switches
#    type: P4_NETRONOME
#    rtecliPath: /opt/nfp-sdk-6.0.1/p4/bin/rtecli
#    switches:
#      - dataplaneId: 100
#        rteIp: 127.0.0.1
#        rtePort: 20206
#        numberOfPorts: 2
#        tableSpecs:
#          # List all files with relevant P4 table specs here
#          - path/to/my_p4_program.p4
#        tableMap:
#            # [Our TableID towards Controller] : [TableID of Switch]
#            3: 0
#        portMap:
#            # [Local Port of Device] : [Our DataplaneID]
#            1: 2
#            2: 2